version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - "./www:/www/"
      - "./site.conf:/etc/nginx/conf.d/site.conf"
    links:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - "./www/:/www/"
    links:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "db-volume:/var/lib/mysql"
      - "./www/dados/1.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_dany
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    ports:
      - 8081:80
volumes:
  db-volume:
  dados: