version: '3.8'

networks:
  wordpress_net:
    driver: bridge

services:
  web:
    image: nginx:latest
    container_name: nginx
    networks:
      - wordpress_net
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./www:/www/"
      - "./site.conf:/etc/nginx/conf.d/site.conf"
    links:
      - php
  php:
    #image: php:7.2-fpm-alpine
    image: cananeadouglas/delicia_php:latest
    #build: .
    container_name: php-fpm
    networks:
      - wordpress_net
    volumes:
      - "./www/:/www/"
    links:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    networks:
      - wordpress_net
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "db-volume:/var/lib/mysql"
      - "./www/dados/1.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_dany
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks:
      - wordpress_net
    links:
      - db
    ports:
      - 8081:80

volumes:
  db-volume:
  dados: